name: Build and Deploy (staging)

# Called by Checks once it passes on a push to staging.
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging

    permissions:
      contents: read

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: PATH
          script: |
            set -e
            sudo /opt/relaysms/relaysms-publisher/manage.sh update
